### ISSUE TITLE
Undefined class constant 'SCOPE_DEFAULT' during upgrade (manually installed)

### ISSUE THREAD

**Issue by VesnaS** [EmicoEcommerce/Magento2TweakwiseExport-archived#34]
Hello,

We just installed the latest release of the extension.
When trying to run setup:upgrade command, we get the following error:

```
PHP Fatal error:  Uncaught Error: Undefined class constant 'SCOPE_DEFAULT' in /vagrant/app/code/Emico/TweakwiseExport/Model/Config.php:99
Stack trace:
#0 /vagrant/app/code/Emico/TweakwiseExport/Console/Command/ExportCommand.php(67): Emico\TweakwiseExport\Model\Config->isValidate()
#1 /vagrant/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(65): Emico\TweakwiseExport\Console\Command\ExportCommand->configure()
#2 /vagrant/app/code/Emico/TweakwiseExport/Console/Command/ExportCommand.php(53): Symfony\Component\Console\Command\Command->__construct()
#3 /vagrant/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Emico\TweakwiseExport\Console\Command\ExportCommand->__construct(Object(Emico\TweakwiseExport\Model\Config), Object(Emico\TweakwiseExport\Model\Export\Proxy), Object(Magento\Framework\App\State))
#4 /vagrant/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Emico\\Tweakwise...', Array)
#5 / in /vagrant/app/code/Emico/TweakwiseExport/Model/Config.php on line 99

Fatal error: Uncaught Error: Undefined class constant 'SCOPE_DEFAULT' in /vagrant/app/code/Emico/TweakwiseExport/Model/Config.php on line 99

Error: Undefined class constant 'SCOPE_DEFAULT' in /vagrant/app/code/Emico/TweakwiseExport/Model/Config.php on line 99

Call Stack:
    0.0004     350440   1. {main}() /vagrant/bin/magento:0
    0.2497     524800   2. Magento\Framework\Console\Cli->__construct() /vagrant/bin/magento:22
    1.3081    7192272   3. Magento\Framework\Console\Cli->__construct() /vagrant/vendor/magento/framework/Console/Cli.php:83
    1.3319    7285488   4. Magento\Framework\Console\Cli->getDefaultCommands() /vagrant/vendor/symfony/console/Symfony/Component/Console/Application.php:91
    1.3353    7361864   5. Magento\Framework\Console\Cli->getApplicationCommands() /vagrant/vendor/magento/framework/Console/Cli.php:112
    2.2720   11016952   6. Magento\Framework\ObjectManager\ObjectManager->create() /vagrant/vendor/magento/framework/Console/Cli.php:144
    2.2720   11016952   7. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/vendor/magento/framework/ObjectManager/ObjectManager.php:57
    2.2742   11018936   8. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() /vagrant/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:82
    2.2743   11020672   9. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->resolveArgument() /vagrant/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:53
    2.2743   11020672  10. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->parseArray() /vagrant/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:139
    2.7844   13678808  11. Magento\Framework\ObjectManager\ObjectManager->get() /vagrant/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:163
    2.7844   13678808  12. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /vagrant/vendor/magento/framework/ObjectManager/ObjectManager.php:71
    2.7914   13757896  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->createObject() /vagrant/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:89
    2.7914   13758216  14. Emico\TweakwiseExport\Console\Command\ExportCommand->__construct() /vagrant/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
    2.7914   13758216  15. Emico\TweakwiseExport\Console\Command\ExportCommand->__construct() /vagrant/app/code/Emico/TweakwiseExport/Console/Command/ExportCommand.php:53
    2.7914   13758376  16. Emico\TweakwiseExport\Console\Command\ExportCommand->configure() /vagrant/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:65
    2.7917   13758952  17. Emico\TweakwiseExport\Model\Config->isValidate() /vagrant/app/code/Emico/TweakwiseExport/Console/Command/ExportCommand.php:67
```
**Environment**

- PHP 7.0
- Magento 2.1.6
- Deploy mode - developer

**Comment by basselalaraaj** [comment]
same here.
